# Generated by Django 3.0.8 on 2020-08-15 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article')),
            ],
        ),
    ]
