# Generated by Django 3.0.8 on 2020-08-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_option_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article'),
        ),
    ]
