# Generated by Django 3.0.8 on 2020-08-19 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200818_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='admiral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Admiral'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Timeline'),
        ),
    ]
