# Generated by Django 3.0.8 on 2020-08-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200818_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='articleType',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article'),
        ),
    ]
