# Generated by Django 3.0.8 on 2020-08-31 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200821_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='admiral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Admiral'),
        ),
        migrations.AddField(
            model_name='question',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Timeline'),
        ),
        migrations.AlterField(
            model_name='question',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article'),
        ),
    ]
