# Generated by Django 3.0.8 on 2020-09-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20200830_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('admiral', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Admiral')),
                ('article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article')),
                ('timeline', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Timeline')),
            ],
        ),
    ]
